DevSearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls')),
    path('users/', include('users.urls')),
    path('password-reset/', PasswordResetView.as_view(),
     name='password_reset'),
    path('password-reset-done/', PasswordResetDoneView.as_view(),
     name='password_reset_done'),
    path('reset/<token>/<uidb64>/',
     PasswordResetConfirmView.as_view(),
     name='password_reset_confirm'),
    path('password-reset-complete/',
     PasswordResetCompleteView.as_view(),
     name='password_reset_complete'),
]

urlpatterns += static(prefix=settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(prefix=settings.STATIC_URL, document_root=settings.STATIC_ROOT)

api/urls.py
from django.urls import path
from .views import *

from rest_framework.routers import SimpleRouter
router = SimpleRouter()
router.register('news', NewsSetApiView, basename='news'),
router.register('user ', UserSetApiView, basename='user')
urlpatterns = router.urls


#
# urlpatterns = [
#     path('News/', NewsApiView.as_view()),
#     path('News/<int:pk>/', NewsRetrieveApiView.as_view()),
#     path('Newsupdeate/<int:pk>/', NewsUpdateApiView.as_view()),
#     path('Newscreate/', NewsCreateApiView.as_view()),
    #
    # path('properties/', PropertyApiView.as_view()),
    # path('properties/<int:pk>/', PropertyRetrieveApiView.as_view()),
    # path('agent/', AgentApiView.as_view()),
    # path('agent/<int:pk>/', AgentRetrieveApiView.as_view()),
    # path('property/', propertyApiView.as_view()),
    # path('property/<int:pk>/', propertyRetrieveApiView.as_view()),
    # path('comments/', CommentsApiView.as_view()),
    # path('comments/<int:pk>/', AgentRetrieveApiView.as_view()),
#]

projects/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', index),
    path('projects/', projects, name='projects'),
    path('create-project/', createproject, name='create_project'),
    path('single-project/<str:pk>/', singleproject, name='single_project'),
    path('edit-project/<str:pk>/', updateproject, name='edit_project'),
    path('delete-project/<str:pk>/', delete_project, name='delete_project')
]

projects/models.py
from django.db import models
import uuid
from users.models import Profile


# Create your models here.

class Project(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, blank=True, null=True)
    id = models.UUIDField(default=uuid.uuid4, primary_key=True,
                          editable=False, unique=True)
    name = models.CharField(max_length=200, )
    image = models.ImageField(upload_to='project-images/', blank=True, null=True,
                              default='static/images/projects-images/default-image.jpg')
    description = models.TextField(max_length=2000, blank=True, null=True)
    tags = models.ManyToManyField('Tags', blank=True, null=True)
    source_link = models.TextField(max_length=2000, blank=True, null=True)
    demo_link = models.TextField(max_length=2000, blank=True, null=True)
    vote_total = models.IntegerField(default=0, blank=True, null=True)
    vote_ratio = models.IntegerField(default=0, blank=True, null=True)

    def __str__(self):
        return self.name


class Tags(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          editable=False, primary_key=True)

    def __str__(self):
        return self.name


class Reviews(models.Model):
    VOTES = (
        ('like', 'like'),
        ('dislike', 'dislike')
    )
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    text = models.TextField(max_length=2000, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, editable=False,
                          primary_key=True, unique=True)
    body = models.CharField(max_length=200, choices=VOTES, blank=True, null=True)

    def __str__(self):
        return self.text

projects/forms.py
from django import forms
from .models import Project, Tags, Reviews

class ProjectForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={
        "class": "input input--text"
    }))
    description = forms.CharField(widget=forms.Textarea(attrs={
        "class": "input input--text"
    }))
    image = forms.ImageField(widget=forms.FileInput(attrs={
        "class": "input input--text"
    }), required=False)
    tags = forms.ModelMultipleChoiceField(queryset=Tags.objects.all(), widget=forms.CheckboxSelectMultiple(attrs={
        "class": "input input--text"
    }))
    source_link = forms.CharField(widget=forms.TextInput(attrs={
        "class": "input input--text"
    }))
    demo_link = forms.CharField(widget=forms.TextInput(attrs={
        "class": "input input--text"
    }))
    class Meta:
        model = Project
        fields = ('name', 'description', 'image', 'tags', 'source_link', 'demo_link')



class ReviewForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea(attrs={
        "class": "input input--text"
    }))

    class Meta:
        model = Reviews
        fields = ['text', 'body']

projects/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib import messages
from .models import *
from .forms import *


# Create your views here.

def index(request):
    return redirect('developers')

def projects(request):
    search_query = ""
    if request.GET.get('search_query'):
        search_query = request.GET.get('search_query')

    tags = Tags.objects.filter(name__icontains=search_query)

    projects = Project.objects.distinct().filter(
        Q(name__icontains=search_query) |
        Q(tags__in=tags) |
        Q(owner__name__icontains=search_query)
    )
    context = {
        "projects": projects
    }
    return render(request, 'projects.html', context=context)

def singleproject(request, pk):
    project = Project.objects.get(id=pk)
    form = ReviewForm()
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        review = form.save(commit=False)
        review.owner = request.user.profile
        review.project = project
        review.save()
        return redirect('single_project', pk=project.id)
    votes = Reviews.objects.filter(project=project)
    len_votes = len(votes)
    count = 0
    context = {
        'project': project,
        'form': form,
        'votes': len_votes,

    }
    if len_votes != 0:
        count = 0
        for vote in votes:
            if vote.body == 'like':
                count += 1
        positive_vote = 100 / len_votes * count
        context.update({'positive_vote': round(positive_vote)})
    return render(request, 'single-project.html', context)


def createproject(request):
    form = ProjectForm
    profile = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES)
        newtags = request.POST.get('newtags').replace(',' ' ').split()
        if form.is_valid():
            project = form.save(commit=False)
            project.owner = profile
            project.save()
            for tag in newtags:
                tag, created = Tags.objects.get_or_create(name=tag)
                project.tags.add(tag)
                messages.success(request, 'Project qoshildi')
            return redirect('account')
    context = {
        "form": form
    }
    return render(request, 'form-template.html', context=context)


def updateproject(request, pk):
    project = Project.objects.get(id=pk)
    form = ProjectForm(instance=project)
    profile = request.user.profile
    if request.method == 'POST':
        form = ProjectForm(instance=project, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('single_project', pk=pk)
    context = {
        'form': form
    }
    return render(request, 'form-template.html', context)


def delete_project(request, pk):
    profile = request.user.profile

    project = profile.project_set.get(id=pk)

    if request.method == "POST":
        project.delete()
        return redirect('account')
    context = {
        'project': project
    }
    return render(request, 'delete-project.html', context)

projects/templates/delete-project.html
{% extends 'base.html' %}


{% block content %}


<div class="container">
    <form class="form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h1>Are you sure delete this: ({{project}}) ? </h1>
        <a href="{% url 'single_project' pk=project.id %}">Go back</a>
        <button class="btn btn--sub btn--lg  my-md" type="submit" value="Submit">Yes</button>
    </form>

</div>

{% endblock content %}

projects/templates/form-template.html
{% extends 'base.html' %}
{% block content %}
    <!-- Main Section -->
<main class="formPage my-xl" xmlns="http://www.w3.org/1999/html">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="#"><i class="im im-angle-left"></i></a>
                <br>
                <form class="form"  method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <!-- Input:Text -->
                  <div class="form__field">
                        <label for="{{form.name.id_for_label}}">Name </label>
                        {{form.name}}
                    </div>
                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="{{form.description.id_for_label}}">description: </label>
                        {{form.description}}
                    </div>
                    <div class="form__field">
                        <label for="{{form.image.id_for_label}}">tags: </label>
                        {{form.image}}
                    </div>
                    <div class="form__field">
                        <label for="{{form.tags.id_for_label}}">tags: </label>
                        {{form.tags}}
                    </div>
                    <div class="form__field">
                        <label for="{{form.source_link.id_for_label}}">source_link: </label>
                        {{form.source_link}}
                    </div>
                    <div class="form__field">
                        <label for="{{form.demo_link.id_for_label}}">demo_link: </label>
                        {{form.demo_link}}
                    </div>
                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">Tags: </label>
                        <input class="input input--text" id="formInput#text" type="text" name="newtags"
                            placeholder="Enter text" />
                    </div>

                    <button class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" >Submit</button>
                </form>
            </div>
        </div>
    </main>
{% endblock content %}

projects/templates/projects.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <!-- Main Section -->
  <main class="projects">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>Search for <span>Projects</span></h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="{% url 'projects' %}" method="get">
            <div class="form__field">
              <label for="formInput#search">Search By Projects </label>
              <input class="input input--text" id="formInput#search" type="text" name="search_query"
                placeholder="Search by Project Title" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="projectsList">
      <div class="container">
        <div class="grid grid--three">
          {% for project in projects %}
          <div class="column">
            <div class="card project">
              <a href="{% url 'single_project' pk=project.id %}" class="project">
                <img class="project__thumbnail" src="{% if project.image %} {{project.image.url}} {% else %} {% static 'images/project-images/default-image.jpg' %} {% endif %}" alt="project thumbnail" />
                <div class="card__body">
                  <h3 class="project__title">{{project.name}}</h3>
                  <p><a class="project__author" href="profile.html">{{project.owner.name}}</a></p>
                  <p class="project--rating">
                    <span style="font-weight: bold;">98%</span> Postitive
                    Feedback (72 Votes)
                  </p>

                  <div class="project__tags">
                    {% for tag in project.tags.all %}
                    <span class="tag tag--pill tag--main">
                      <small>{{tag}}</small>
                    </span>
                    {% endfor %}
                  </div>
                </div>
              </a>
            </div>
          </div>
          {% endfor %}

        </div>
      </div>
    </section>

    <div class="pagination">
      <ul class="container">
        <li><a href="#" class="btn btn--disabled">&#10094; Prev</a></li>
        <li><a href="#" class="btn btn--sub">01</a></li>
        <li><a href="#" class="btn">02</a></li>
        <li><a href="#" class="btn">03</a></li>
        <li><a href="#" class="btn">04</a></li>
        <li><a href="#" class="btn">05</a></li>
        <li><a href="#" class="btn">06</a></li>
        <li><a href="#" class="btn">07</a></li>
        <li><a href="#" class="btn">08</a></li>
        <li><a href="#" class="btn">09</a></li>
        <li><a href="#" class="btn">10</a></li>
        <li><a href="#" class="btn">Next &#10095;</a></li>
      </ul>
    </div>
  </main>


{% endblock content %}

projects/templates/single-project.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <!-- Main Section -->
  <main class="singleProject my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <h3 class="singleProject__subtitle">{{project.name}}</h3>
          <div class="singleProject__toolStack">
            {% for tag in project.tags.all %}
            <span class="tag tag--pill tag--sub tag--lg">
              <small>{{tag.name}}</small>
            </span>
            {% endfor %}
          </div>
          <a class="singleProject__liveLink" href="#" target="_blank"><i class="im im-external-link"></i>Source Code
          </a>


        </div>
        <div class="column column--2of3">
          <img class="singleProject__preview" src="{% if project.image %} {{project.image.url}} {% else %} {% static 'images/project-images/default-image.jpg' %}  {% endif %}" alt="portfolio thumbnail" />
          <a href="{% url 'profile' pk=project.owner.id %}" class="singleProject__developer">{{project.owner.name}}</a>
          <h2 class="singleProject__title">{{project.name}}</h2>
          <h3 class="singleProject__subtitle">About the Project</h3>
          <div class="singleProject__info">
            {{project.description}}
          </div>

          <div class="comments">
            <h3 class="singleProject__subtitle">Feedback</h3>
            <h5 class="project--rating">
              {{positive_vote}} % Postitive Feedback ({{votes}} Votes)
            </h5>

            <form class="form" action="" method="POST">
              {% csrf_token %}
              <!-- Textarea -->
              <div class="form__field">
                {{form.body}}
               {{ form.text }}
              </div>
              <input class="btn btn--sub btn--lg" type="submit" value="Comments" />
            </form>


            <div class="commentList">
              {% for review in project.reviews_set.all %}
              <div class="comment">
                <a href="{% url 'profile' pk=review.owner.id %}">
                  <img class="avatar avatar--md"
                    src="{{review.owner.image.url}}" alt="user" />
                </a>
                <div class="comment__details">
                  <a href="{% url 'profile' pk=review.owner.id %}" class="comment__author">{{review.owner.name}}</a>
                  <p class="comment__info">
                    {{review.text}}
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>

  </main>
{% endblock content %}